// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9NKW67nQfnDxcAmI_oP6x0m51Bf2C6Y8',
    appId: '1:123791858648:web:a1e810c9ddd60e838f70ad',
    messagingSenderId: '123791858648',
    projectId: 'chakri-info',
    authDomain: 'chakri-info.firebaseapp.com',
    storageBucket: 'chakri-info.firebasestorage.app',
    measurementId: 'G-9ZQG3XQQ8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Jk-0bUDBqkvpo2T09gvDGqIUg3gVICA',
    appId: '1:123791858648:android:00b790c43e5b0f2e8f70ad',
    messagingSenderId: '123791858648',
    projectId: 'chakri-info',
    storageBucket: 'chakri-info.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4wXhmQyl9gZdpSpL9oiD_xi7YhlKjuY',
    appId: '1:123791858648:ios:dba5546e277fc0678f70ad',
    messagingSenderId: '123791858648',
    projectId: 'chakri-info',
    storageBucket: 'chakri-info.firebasestorage.app',
    iosBundleId: 'com.example.chakriInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm4wXhmQyl9gZdpSpL9oiD_xi7YhlKjuY',
    appId: '1:123791858648:ios:dba5546e277fc0678f70ad',
    messagingSenderId: '123791858648',
    projectId: 'chakri-info',
    storageBucket: 'chakri-info.firebasestorage.app',
    iosBundleId: 'com.example.chakriInfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9NKW67nQfnDxcAmI_oP6x0m51Bf2C6Y8',
    appId: '1:123791858648:web:05d15e1f268ade248f70ad',
    messagingSenderId: '123791858648',
    projectId: 'chakri-info',
    authDomain: 'chakri-info.firebaseapp.com',
    storageBucket: 'chakri-info.firebasestorage.app',
    measurementId: 'G-WBGYBFQ9XV',
  );

}